use customer_behavior;
-- Q1 what is the revenue generated by Male vs Female customers??
select gender , sum(purchase_amount) as revenue
from customer
group by gender;

-- Q2. Which customer used a discount but still spent more than the average purchase amount?
 select customer_id, purchase_amount
 from customer
 where discount_applied= 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);
 
 select * from customer;
 
 -- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(AVG(review_rating),2) as "Average Product Rating"
from customer
group by item_purchased
order by AVG(review_rating) desc
limit 5;

-- Q4 Compare the avergae purchase amounts between Standard and Express Shipping
select round(avg(purchase_amount), 2), shipping_type
from customer
where shipping_type in ("Standard" ,"Express")
group by shipping_type;

-- Q5 Do subscribed customer spend more? Compare Average spend and Total revenue between subscribers
-- and non-subscribers
 select subscription_status, 
 count(customer_id) as customers,
 round(Avg(purchase_amount), 2) as "Average Spend", 
 round(sum(purchase_amount), 2) as "Total Revenue"
 from customer
 group by subscription_status
 order by "Total revenue", "Average Spend" desc;
 
 -- Q6 Which 5 products have the highest percentage of purchases with discount applied?
 select item_purchased as "Products", previous_purchases, discount_applied
 from customer
 group by discount_applied
 having discount_applied = "Yes"
 limit 5;
 
 
 


